# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190324_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWDReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_code', models.CharField(max_length=24)),
                ('valid_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
    ]
