# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('summary', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=2000)),
                ('long', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
            ],
        ),
    ]
