# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='long',
            new_name='lng',
        ),
    ]
