# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0003_auto_20190428_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2000)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '转发',
                'verbose_name_plural': '转发',
                'ordering': ['-c_time'],
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='repost',
        ),
        migrations.AddField(
            model_name='repost',
            name='repost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.Event'),
        ),
    ]
