# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20190512_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='event_image/%Y%m%d/'),
        ),
    ]
