# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0005_auto_20190514_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repost',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='repost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
        migrations.AddField(
            model_name='event',
            name='repost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='repost_comment',
            field=models.CharField(default='none', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='reposter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
