# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20190514_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='reposter',
            new_name='owner',
        ),
    ]
