# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20190514_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='repost_comment',
            new_name='repostcomment',
        ),
    ]
