# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20190515_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='event_image/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repost',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.Event'),
        ),
    ]
