# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20190519_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repost',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.Event'),
        ),
    ]
