# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20190519_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repostcomment',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
