"""
Django settings for GalaX project.

Generated by 'django-admin startproject' using Django 1.11.20.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fp61n_5@950s3n5e9lc^d3!i!wioz4lv$eb427+ke611i9*php'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'map',
    'user_information.apps.UserInformationConfig',
    'login',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GalaX.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GalaX.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
"""
#Tang:Please use this for you mysql database,don't change mysql's default localhost port.
#For UESR name,if you don't change default setting,it is root.Or you can change it to your username.
#I recommend to use the sql file in QQ group.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Galax_database',
        'USER': 'Galax_database_admin',
        'PASSWORD': '123test567',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
#English is 'en-us'
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
# static set
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    
]

# Email setting
"""
IMAP 服务器名称outlook.office365.com

IMAP 端口 993

IMAP 加密方法TLS

POP 服务器名称outlook.office365.com

POP 端口 995

POP 加密方法 TLS

SMTP 服务器名称smtp.office365.com

SMTP 端口 587

SMTP 加密方法 STARTTLS
"""
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Email host，we use outlook in QQ group bulletin
EMAIL_HOST = 'smtp-mail.outlook.com'
#EMAIL_HOST = 'smtp.office365.com'
#EMAIL_HOST = 'smtp.live.com'

#(port 25 or 587)
EMAIL_PORT = 587
EMAIL_HOST_USER = 'galax_developer@outlook.com'
# 自己的邮箱授权码，非密码
EMAIL_HOST_PASSWORD = 'mlgxkbopsyvffyri'
EMAIL_USE_TLS = True

#Other email setting may use

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
#Subject-line prefix for email messages sent with django.core.mail.mail_admins or django.core.mail.mail_managers. You’ll probably want to include the trailing space
#EMAIL_SUBJECT_PREFIX=
#Longest time avaliable for register
CONFIRM_DAYS = 2


# captcha setting
CAPTCHA_IMAGE_SIZE=(100, 30)
CAPTCHA_TIMEOUT = '2'
CAPTCHA_LENGTH = '4'
